title: <p align="center"> Dila Kiranti </p>

logo: "/images/picture1.png?raw=true"

description:
  <p align="center">
  <a href="pdf/Resume_dilakiranti.pdf">Resume</a> |
  <a href="https://www.linkedin.com/in/dilakiranti/">LinkedIn</a> |
  <a href="https://github.com/dilakiranti">GitHub</a>
  </p>
  
  <p align="justify">
  I am an undergraduate student of Statistics at Diponegoro University
  <br><br>
  I have interest in data analyst and data science. I am currently learning data analytics and machine learning. I have the ability to use programming languages such as SQL, Python, and R.
  <br><br>
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
